### ISSUE TITLE
brigade.js dependencies not resolving

### ISSUE THREAD

**Issue by vishu42** [technosophos/brigtest#3]
**Problem statement**
I have a brigade.js file with a dependency `const jest = require('./jest.config.js');`, when I am trying to run `brigtest ./brigade.js`, I get the following error

`[internal/modules/cjs/loader.js:968
  throw err;
  ^

  Error: Cannot find module './jest.config.js'
  Require stack:
  - /home/vishal.tewatia/github/brigadecore/brigtest/src/index.js
  
  - loader.js:965 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:965:15
  
  - loader.js:841 Function.Module._load
    internal/modules/cjs/loader.js:841:27
  
  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19
  
  - helpers.js:72 require
    internal/modules/cjs/helpers.js:72:18
  
  - index.js:65 overridingRequire
    /home/vishal.tewatia/github/brigadecore/brigtest/src/index.js:65:10
  
  - brigade.js:9 
    /home/vishal.tewatia/dan/platform/media-ecosystem/brigade.js:9:14
  
  - index.js:78 Object.<anonymous>
    /home/vishal.tewatia/github/brigadecore/brigtest/src/index.js:78:3
  
  - loader.js:1137 Module._compile
    internal/modules/cjs/loader.js:1137:30
  
  - loader.js:1157 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1157:10
  
] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/vishal.tewatia/github/brigadecore/brigtest/src/index.js' ]
`

**Expected result**
It should have been able to fine the dependency as its present there and continued execution.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
